# Generated by Django 3.1a1 on 2020-06-15 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('thumbnail', models.ImageField(upload_to='channel_thumbnails', verbose_name='thumbnail')),
                ('image', models.ImageField(upload_to='channel_images', verbose_name='image')),
            ],
            options={
                'verbose_name': 'channel',
                'verbose_name_plural': 'channels',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=40, verbose_name='title')),
                ('youtube_id', models.CharField(blank=True, max_length=20, verbose_name='youtube video')),
                ('instagram_url', models.CharField(blank=True, max_length=40, verbose_name='instagram url')),
                ('address', models.CharField(default='', max_length=30, verbose_name='address')),
                ('phone_number', models.CharField(default='', max_length=13, verbose_name='phone number')),
                ('price', models.CharField(blank=True, max_length=3, verbose_name='price')),
                ('biztime', models.TextField(blank=True, verbose_name='biztime')),
                ('breaktime', models.TextField(blank=True, verbose_name='breaktime')),
                ('info', models.TextField(blank=True, verbose_name='info')),
                ('menu', models.TextField(blank=True, verbose_name='menu')),
                ('holiday', models.CharField(blank=True, max_length=3, verbose_name='holiday')),
                ('category', models.ManyToManyField(blank=True, related_name='restaurant', to='restaurants.Category', verbose_name='category')),
                ('channel', models.ManyToManyField(blank=True, related_name='restaurant', to='restaurants.Channel', verbose_name='channel')),
                ('tag_set', models.ManyToManyField(blank=True, related_name='restaurant', to='restaurants.Tag', verbose_name='tag set')),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(blank=True, max_length=80, verbose_name='caption')),
                ('file', models.ImageField(upload_to='restaurant_photos', verbose_name='file')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='restaurants.restaurant', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
    ]
