# Generated by Django 3.1b1 on 2020-06-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=40, verbose_name='instagram link'),
        ),
        migrations.AddField(
            model_name='channel',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='rank'),
        ),
        migrations.AddField(
            model_name='channel',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=40, verbose_name='youtube link'),
        ),
        migrations.AddField(
            model_name='youtube',
            name='name',
            field=models.CharField(default='', max_length=80, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='channel_thumbnails', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price',
            field=models.CharField(blank=True, max_length=20, verbose_name='price'),
        ),
    ]
