# Generated by Django 3.1a1 on 2020-06-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='name',
            field=models.CharField(default='', max_length=80, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price',
            field=models.CharField(blank=True, max_length=20, verbose_name='price'),
        ),
    ]
