# Generated by Django 3.1b1 on 2020-07-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200623_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='biztime',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='biztime_24',
            field=models.BooleanField(default=False, verbose_name='biztime 24'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='biztime_end',
            field=models.TimeField(blank=True, null=True, verbose_name='biztime end'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='biztime_start',
            field=models.TimeField(blank=True, null=True, verbose_name='biztime start'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='holiday',
            field=models.CharField(blank=True, choices=[('월요일', 'Monday'), ('화요일', 'Tuesday'), ('수요일', 'Wednesday'), ('목요일', 'Thursday'), ('금요일', 'Friday'), ('토요일', 'Saturday'), ('일요일', 'Sunday')], default=None, max_length=10, verbose_name='holiday'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(default='', max_length=13, unique=True, verbose_name='phone number'),
        ),
    ]
