# Generated by Django 3.1b1 on 2020-06-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200616_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=40, verbose_name='instagram link'),
        ),
        migrations.AddField(
            model_name='channel',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='rank'),
        ),
        migrations.AddField(
            model_name='channel',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=40, verbose_name='youtube link'),
        ),
    ]
