# Generated by Django 3.1b1 on 2020-07-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20200701_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='biztime_desc',
            field=models.CharField(blank=True, max_length=30, verbose_name='biztime_desc'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='blog_count',
            field=models.CharField(blank=True, max_length=15, verbose_name='blog_count'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='naver_place_id',
            field=models.CharField(blank=True, max_length=15, verbose_name='naver_place_id'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tv_list',
            field=models.TextField(blank=True, verbose_name='tv_list'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='holiday',
            field=models.CharField(blank=True, choices=[('월요일', 'Monday'), ('화요일', 'Tuesday'), ('수요일', 'Wednesday'), ('목요일', 'Thursday'), ('금요일', 'Friday'), ('토요일', 'Saturday'), ('일요일', 'Sunday')], max_length=10, verbose_name='holiday'),
        ),
    ]
