# Generated by Django 3.1rc1 on 2020-07-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20200720_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='x',
            field=models.FloatField(blank=True, null=True, verbose_name='x'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='y',
            field=models.FloatField(blank=True, null=True, verbose_name='y'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=30, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='naver_place_id',
            field=models.CharField(max_length=15, unique=True, verbose_name='naver_place_id'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='title',
            field=models.CharField(blank=True, max_length=40, verbose_name='title'),
        ),
    ]
